version: '3.7'

services:
  mongobd :
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
        MONGO_INITDB_DATABASE: pixerart
    ports:
        - 27017:27017
        - 9229:9229
    volumes:
        - ./mongo-init/:/docker-entrypoint-initdb.d/:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8111:8081 
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongobd
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin